[package]
name = "generator"
version = "0.1.0"
authors = ["Christian De la Hoz <christian.hoz@anixe.pl>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
egui = "0.11.0"
rand = "0.8.3"
